# Generated by Django 5.2.7 on 2025-10-24 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('reserva_confirmada', 'Reserva Confirmada'), ('reserva_cancelada', 'Reserva Cancelada'), ('clase_cancelada', 'Clase Cancelada'), ('cupo_disponible', 'Cupo Disponible'), ('recordatorio', 'Recordatorio'), ('bloqueo', 'Bloqueo de Cuenta'), ('otros', 'Otros')], max_length=30, verbose_name='Tipo de Notificación')),
                ('canal', models.CharField(choices=[('email', 'Email'), ('push', 'Push Notification'), ('sms', 'SMS'), ('sistema', 'Sistema')], default='sistema', max_length=20, verbose_name='Canal')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviada', 'Enviada'), ('fallida', 'Fallida'), ('leida', 'Leída')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('datos_adicionales', models.JSONField(blank=True, help_text='Información adicional en formato JSON', null=True, verbose_name='Datos Adicionales')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_envio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Envío')),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Lectura')),
                ('intentos_envio', models.IntegerField(default=0, verbose_name='Intentos de Envío')),
                ('error_mensaje', models.TextField(blank=True, verbose_name='Mensaje de Error')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
