# Generated by Django 5.2.7 on 2025-10-24 18:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Clase')),
                ('tipo', models.CharField(choices=[('spinning', 'Spinning'), ('yoga', 'Yoga'), ('pilates', 'Pilates'), ('musculacion', 'Musculación'), ('cardio', 'Cardio')], max_length=20, verbose_name='Tipo de Clase')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de Inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora de Fin')),
                ('cupos_totales', models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cupos Totales')),
                ('cupos_ocupados', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cupos Ocupados')),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('cancelada', 'Cancelada'), ('completada', 'Completada')], default='activa', max_length=20, verbose_name='Estado')),
                ('permite_lista_espera', models.BooleanField(default=True, verbose_name='Permite Lista de Espera')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Clase',
                'verbose_name_plural': 'Clases',
                'ordering': ['fecha', 'hora_inicio'],
            },
        ),
    ]
