# Generated by Django 5.2.7 on 2025-10-24 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clases', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clases', to='usuarios.instructor', verbose_name='Instructor'),
        ),
        migrations.AddIndex(
            model_name='clase',
            index=models.Index(fields=['fecha', 'tipo'], name='clases_clas_fecha_4a760e_idx'),
        ),
        migrations.AddIndex(
            model_name='clase',
            index=models.Index(fields=['estado'], name='clases_clas_estado_f92e6c_idx'),
        ),
    ]
