# Generated by Django 5.2.7 on 2025-12-16 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='clases/', verbose_name='Imagen de la Clase'),
        ),
    ]
