# Generated by Django 5.2.7 on 2025-10-24 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaEspera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('esperando', 'Esperando'), ('asignado', 'Asignado'), ('expirado', 'Expirado'), ('cancelado', 'Cancelado')], default='esperando', max_length=20, verbose_name='Estado')),
                ('posicion', models.IntegerField(default=0, verbose_name='Posición en la Lista')),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Ingreso')),
                ('fecha_asignacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Asignación')),
                ('fecha_expiracion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Expiración')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('notificacion_enviada', models.BooleanField(default=False, verbose_name='Notificación Enviada')),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lista_espera', to='clases.clase', verbose_name='Clase')),
            ],
            options={
                'verbose_name': 'Lista de Espera',
                'verbose_name_plural': 'Listas de Espera',
                'ordering': ['clase', 'posicion', 'fecha_ingreso'],
            },
        ),
    ]
