# Generated by Django 5.2.7 on 2025-10-24 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lista_espera', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='listaespera',
            name='socio',
            field=models.ForeignKey(limit_choices_to={'rol': 'socio'}, on_delete=django.db.models.deletion.CASCADE, related_name='lista_espera', to=settings.AUTH_USER_MODEL, verbose_name='Socio'),
        ),
        migrations.AddIndex(
            model_name='listaespera',
            index=models.Index(fields=['clase', 'estado', 'posicion'], name='lista_esper_clase_i_899a37_idx'),
        ),
        migrations.AddIndex(
            model_name='listaespera',
            index=models.Index(fields=['socio', 'estado'], name='lista_esper_socio_i_d797d9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='listaespera',
            unique_together={('socio', 'clase')},
        ),
    ]
