# Generated by Django 5.2.7 on 2025-10-24 18:38

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rol', models.CharField(choices=[('socio', 'Socio'), ('instructor', 'Instructor'), ('administrador', 'Administrador')], default='socio', max_length=20, verbose_name='Rol')),
                ('telefono', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="El teléfono debe estar en formato: '+999999999'. Hasta 15 dígitos.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Teléfono')),
                ('estado_membresia', models.CharField(choices=[('activa', 'Activa'), ('inactiva', 'Inactiva'), ('suspendida', 'Suspendida')], default='activa', max_length=20, verbose_name='Estado de Membresía')),
                ('fecha_inicio_membresia', models.DateField(blank=True, null=True, verbose_name='Fecha Inicio Membresía')),
                ('fecha_fin_membresia', models.DateField(blank=True, null=True, verbose_name='Fecha Fin Membresía')),
                ('total_noshow', models.IntegerField(default=0, verbose_name='Total No-Shows')),
                ('noshow_mes_actual', models.IntegerField(default=0, verbose_name='No-Shows del Mes Actual')),
                ('bloqueado_hasta', models.DateTimeField(blank=True, null=True, verbose_name='Bloqueado Hasta')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['-fecha_creacion'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidades', models.CharField(blank=True, help_text='Ej: Spinning, Yoga, Pilates', max_length=200, verbose_name='Especialidades')),
                ('biografia', models.TextField(blank=True, verbose_name='Biografía')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='instructores/', verbose_name='Foto')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_instructor', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Instructor',
                'verbose_name_plural': 'Instructores',
                'ordering': ['usuario__first_name'],
            },
        ),
    ]
