# Generated by Django 5.2.7 on 2025-12-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='certificaciones',
            field=models.TextField(blank=True, help_text='Certificaciones y títulos del instructor', verbose_name='Certificaciones'),
        ),
    ]
