# Generated by Django 5.2.7 on 2025-12-08 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Equipo')),
                ('categoria', models.CharField(choices=[('cardio', 'Cardio'), ('fuerza', 'Fuerza'), ('peso_libre', 'Peso Libre'), ('funcional', 'Funcional'), ('otro', 'Otro')], default='fuerza', max_length=20, verbose_name='Categoría')),
                ('marca', models.CharField(blank=True, max_length=100, verbose_name='Marca')),
                ('modelo', models.CharField(blank=True, max_length=100, verbose_name='Modelo')),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Número de Serie')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('ubicacion', models.CharField(blank=True, help_text='Ej: Sala de Cardio, Sala de Pesas', max_length=100, verbose_name='Ubicación')),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('en_uso', 'En Uso'), ('mantenimiento', 'En Mantenimiento'), ('fuera_servicio', 'Fuera de Servicio')], default='disponible', max_length=20, verbose_name='Estado')),
                ('fecha_compra', models.DateField(blank=True, null=True, verbose_name='Fecha de Compra')),
                ('ultimo_mantenimiento', models.DateField(blank=True, null=True, verbose_name='Último Mantenimiento')),
                ('proximo_mantenimiento', models.DateField(blank=True, null=True, verbose_name='Próximo Mantenimiento')),
                ('notas_mantenimiento', models.TextField(blank=True, verbose_name='Notas de Mantenimiento')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'ordering': ['categoria', 'nombre'],
            },
        ),
    ]
