# Generated by Django 5.2.7 on 2025-12-10 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamiento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Imagen o foto del equipo', null=True, upload_to='equipos/', verbose_name='Imagen del Equipo'),
        ),
    ]
