# Generated by Django 5.2.7 on 2025-10-24 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='socio',
            field=models.ForeignKey(limit_choices_to={'rol': 'socio'}, on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to=settings.AUTH_USER_MODEL, verbose_name='Socio'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['socio', 'estado'], name='reservas_re_socio_i_2a7f9d_idx'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['clase', 'estado'], name='reservas_re_clase_i_6dc9b2_idx'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['fecha_reserva'], name='reservas_re_fecha_r_286145_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reserva',
            unique_together={('socio', 'clase')},
        ),
    ]
