# Generated by Django 5.2.7 on 2025-10-24 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reserva',
            unique_together=set(),
        ),
    ]
